"""Feed a video's Kokoro voice, word timings and sounds into its fframes project.

    npm run fframes-sync -- <slug> --fps <N>

Reads videos/<slug>/voiceover.json (after `npm run voice`) and writes
videos/<slug>/fframes/src/timing.rs: per scene, its length in frames (the same
ceil((durationSeconds + paddingSeconds) x fps) as src/lib/timing.ts), its first
frame in the whole video, its spoken words with their start frame (rounded half up,
like `wordFrame`), and its caption split into the words to show, punctuation kept,
each with the frame it is spoken on.
It also links every narration WAV (audio/) and sound effect (assets/sound/) into
videos/<slug>/fframes/assets/, the folder the project loads at runtime with
`MediaDirectory::read_folder("assets")`.

Run it again after every `npm run voice` or `npm run sound`.
"""

import argparse
import json
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def const_name(scene_id: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", scene_id).upper()


def rust_str(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("video")
    parser.add_argument("--fps", type=int, required=True, help="the fframes Video::FPS")
    args = parser.parse_args()

    video = ROOT / "videos" / args.video
    project = video / "fframes"
    if not (project / "Cargo.toml").exists():
        raise SystemExit(f"{project} has no Cargo.toml. Create it with cargo fframes new first.")
    voiceover = json.loads((video / "voiceover.json").read_text())

    lines = [
        "// Generated by `npm run fframes-sync` from voiceover.json. Do not edit.",
        "#![allow(dead_code)]",
        "",
        f"pub const FPS: usize = {args.fps};",
        "",
    ]
    ids = []
    start = 0
    for scene in voiceover["scenes"]:
        if not scene.get("durationSeconds") or not scene.get("words"):
            raise SystemExit(f'Scene "{scene["id"]}" has no voice yet. Run: npm run voice -- {args.video}')
        name = const_name(scene["id"])
        ids.append(name)
        frames = math.ceil(round((scene["durationSeconds"] + scene["paddingSeconds"]) * args.fps, 3))
        words = ", ".join(
            f'({rust_str(w["text"])}, {math.floor(w["start"] * args.fps + 0.5)})' for w in scene["words"]
        )
        audio = Path(scene["audioFile"]).name
        shown_text = scene.get("caption") or scene["text"]
        tokens = shown_text.split()
        if len(tokens) != len(scene["words"]):
            print(f'warning: scene "{scene["id"]}" shows {len(tokens)} words but says {len(scene["words"])}; '
                  f"{name}_SHOWN pairs them by position up to the shorter list")
        shown = ", ".join(
            f'({rust_str(t)}, {math.floor(w["start"] * args.fps + 0.5)})' for t, w in zip(tokens, scene["words"])
        )
        lines += [
            f"/// {scene['id']}",
            f"pub const {name}_FRAMES: usize = {frames};",
            f"/// First frame of the scene in the whole video, for `frame.global_index` maths.",
            f"pub const {name}_START: usize = {start};",
            f"pub const {name}_AUDIO: &str = {rust_str(audio)};",
            f"pub const {name}_TEXT: &str = {rust_str(scene.get('caption') or scene['text'])};",
            f"/// Each spoken word and the scene-relative frame it starts on.",
            f"pub const {name}_WORDS: &[(&str, usize)] = &[{words}];",
            f"/// The caption's words as shown (punctuation kept), each with the frame it is spoken on.",
            f"pub const {name}_SHOWN: &[(&str, usize)] = &[{shown}];",
            "",
        ]
        start += frames
    total = " + ".join(f"{n}_FRAMES" for n in ids)
    lines.append(f"pub const TOTAL_FRAMES: usize = {total};")
    (project / "src" / "timing.rs").write_text("\n".join(lines) + "\n")

    assets = project / "assets"
    assets.mkdir(exist_ok=True)
    linked = []
    for folder in (video / "audio", video / "assets" / "sound"):
        for wav in sorted(folder.glob("*.wav")) if folder.exists() else []:
            link = assets / wav.name
            if link.is_symlink() or link.exists():
                link.unlink()
            link.symlink_to(Path("..") / ".." / wav.relative_to(video))
            linked.append(wav.name)

    print(f"wrote {project.relative_to(ROOT)}/src/timing.rs ({len(ids)} scenes)")
    print(f"total: {start} frames = {start / args.fps:.3f} s (use this for npm run sound --seconds)")
    print(f"linked into {assets.relative_to(ROOT)}: {', '.join(linked) or 'nothing'}")


if __name__ == "__main__":
    main()
